### ISSUE TITLE
NVelocity 

### ISSUE THREAD

**Issue by phillip-haydon** [castleproject/MonoRail#27]
Hey,

I'm still using NVelocity at work, however we are slowly upgrading our projects to .NET Core.

One of the only projects that I cannot remove and isn't on .NET Core is NVelocity. 

I pulled all the files from this deprecated repository and re-created NVelocity as a .NET Standard 2.0 project.

https://github.com/phillip-haydon/NVelocity.Core

And have it running in App Veyor. 

It's running on Windows with 1 failing test and Ubuntu with 2 failing tests.

https://ci.appveyor.com/project/phillip-haydon/nvelocity-core/build/1.0.10

What I want to know is, what am I required to do as part of the Apache license in order to make sure I don't do anything wrong?

**Comment by jonorossi** [comment]
> What I want to know is, what am I required to do as part of the Apache license in order to make sure I don't do anything wrong?

IANAL, but you'll find the license is pretty flexible. I'd read the [Apache page on this topic](http://www.apache.org/foundation/license-faq.html) since this project is a port of the Apache Velocity project and the trademarks, etc part of the license obviously comes into effect. Our port and extensions/bugfixes over the last decade+ are all licensed under Apache 2.0.

The Castle logo is not explicitly licensed under Apache 2.0 and shouldn't be used in a fork, nor would it be advisable for your fork to be confused with Castle's NVelocity.

> One of the only projects that I cannot remove and isn't on .NET Core is NVelocity.
> 
> I pulled all the files from this deprecated repository and re-created NVelocity as a .NET Standard 2.0 project.
> 
> https://github.com/phillip-haydon/NVelocity.Core

Just to give you some background on this deprecated organisation, it basically houses anything without a somewhat active maintainer it doesn't necessarily mean the project is dead. What we have been finding lately is interest in rebooting specific older projects and getting .NET Standard support exactly like you are doing here.

It is obviously completely your call because the license is flexible, but we could move the NVelocity codebase (without MonoRail) back into the main organisation if you'd like reboot the codebase with a CI build and the likes there rather than on your own, which might encourage others to work with you. There is obviously no commitment to remain a maintainer in future once the initial work is done.

**Comment by phillip-haydon** [comment]
I wouldn't have any issue at all having the codebase in the main organisation. That would be ideal as I suspect other people may want to use it also.

I can help out now-n-then. As long as no one minds that I can only really help out on the weekends. 

What do you need me to do?

**Comment by jonorossi** [comment]
@phillip-haydon sorry for the delay, I've just created a new repository in the main organisation and imported the source code. Let's move there.

https://github.com/castleproject/NVelocity/issues/1
